### ISSUE TITLE
您好，想请问是否能对您的项目进行重构

### ISSUE THREAD

**Issue by misaki-nyanya** [oozonomomoko/blog#1]
您好，感谢您的辛勤劳动，能让我们看到毕业成员的文字！

我考虑对您的网站进行修改，使之在本地也能查看，并且想加入尚未毕业的成员的内容，不知您是否反对这样的修改。

另外，为了收集的数据的统一性，想请教您使用的爬虫？

期待您的回复！

**Comment by oozonomomoko** [comment]
这网站可以访问啊，https://oozonomomoko.github.io/blog/v1/blogList.html
我隔段时间会提交一下的
不过没法按照成员查看博客。
爬虫用的java Jsoup

**Comment by misaki-nyanya** [comment]
感谢回复，并非您的网站不能查看，只是我有想在没有网络的情况下也能阅读的小小的私心...😂🙏

P.S. 听说优蛋也要毕业了，感觉历史的车轮阻挡不住了。。。。。。
P.P.S 关于翻译部分如果有需要帮忙的话我姑且也可以出微薄之力。。。。

**Comment by oozonomomoko** [comment]
这数据随便下载啊，我又没这些博客的版权啥的。。。

**Comment by oozonomomoko** [comment]
额，你说的是要多，你说的是要改我这的代码是吧。。
当时没咋用过git，没明白你说的啥意思😂。

**Comment by misaki-nyanya** [comment]
感谢回信，
抱歉长期没有看GitHub，其实我也有点忘了自己当初的想法/(ㄒoㄒ)/~~
大概是因为您的code里面硬编码了您的host的地址，光下载repo并不能直接在本地看的问题……

**Comment by oozonomomoko** [comment]
本地好像确实不大好看，内容全存成json格式的文件了
